<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <title> Ernz Transport Services </title>\n";
echo "    <meta charset = \"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <link rel=\"stylesheet\" href=\"Home.css\">\n";
echo "	<link rel=\"stylesheet\" href=\"signUpForm.css\">\n";
echo "  </head>\n";
echo "    <body>\n";
echo "		<div>\n";
echo "        <header>\n";
echo "          <a href=\"index.html\" class=\"header-brand\">Ernz Transport</a>\n";
echo "          <nav>\n";
echo "              <ul>\n";
echo "                <li><a href=\"home.html\">Home</a></li>\n";
echo "              </ul>\n";
echo "          </nav>  \n";
echo "\n";
echo "		  <nav>\n";
echo "              <ul>\n";
echo "                <li><a href=\"Cars.html\">Cars</a></li>\n";
echo "              </ul>\n";
echo "          </nav>  \n";
echo "        </header>\n";
echo "		</div>\n";
echo "		  <main>\n";
echo "            <div class=\"wrapper\">\n";
echo "              <section class=\"Home-banner\">\n";
echo "                <div class=\"first-main\">\n";
echo "                  <br> <br>\n";
echo "				  <img src=\"car1.png\">\n";
echo "                  <h1>ERNZ TRANSPORT </h1>\n";
echo "				  <hr>\n";
echo "                  <h2>Manila's Finest Car Renting Service</h2>\n";
echo "              </section>\n";
echo "              <section class=\"Home-banner-boxlink\">\n";
echo "			  </div>\n";
echo "              </section> \n";
echo "			  \n";
echo "			</div>\n";
echo "		  </main>\n";
echo "		  \n";
echo "		  \n";
echo "	<div id='login'>\n";
echo "		<h1>Registration Form</h1>\n";
echo "		<form id='regi_form' action='' method=''>\n";
echo "			<div class='custId'>\n";
echo "			Customer ID No.\n";
echo "				<input type='text' name='idno.' readonly> <br>\n";
echo "			</div>\n";
echo "			<div class='name'>\n";
echo "				<div><input class='names' type='text'  name='Lname' placeholder='Last Name' / > </div>\n";
echo "				<div><input class='names' type='text'  name='Fname' placeholder='First Name' / > </div>\n";
echo "				<div><input class='names' type='text'  name='Mname' placeholder='Middle Name' / > </div>\n";
echo "			</div>\n";
echo "			\n";
echo "			<div class='cred'>\n";
echo "				<div><input class='credss' type='email' 'name='contact_email' pattern='[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,3}$' placeholder='e-mail address'/ >	</div>\n";
echo "				<div><input class='credss' type='text'  name='Uname' placeholder='Username'/ ></div>\n";
echo "				<div><input class='credss' type='password'  name='password' placeholder='password'/ ></div>\n";
echo "				<div><input class='credss' type='password'  name='password' placeholder='confirm password'/ ></div> \n";
echo "			</div>\n";
echo "			\n";
echo "			<div class='addresss'>\n";
echo "				<div><input class='address' type='text'  name='address' placeholder='address'/> </div>\n";
echo "				\n";
echo "				<div><input class='cons' type='text' maxlength='11'  pattern='[0-9]'name='contact' placeholder='contact'/ ></div>\n";
echo "				\n";
echo "			<div><input class='cons' type='text' maxlength='7'  pattern='[0-9]'name='contact_landline' placeholder='landline'/ ></div>\n";
echo "			\n";
echo "			</div>\n";
echo "		<div id='blocks'>\n";
echo "			\n";
echo "			<div class='others'>\n";
echo "			<div><input class='others' type='text' minlength='2'  pattern='[0-9]'name='age' placeholder='age'/ ></div>\n";
echo "\n";
echo "			<div class='sex'>\n";
echo "			Sex:\n";
echo "				<input type='radio' name='sex' value='male'> Male\n";
echo "				<input type='radio' name='sex' value='female'> Female	\n";
echo "			</div>\n";
echo "			\n";
echo "			\n";
echo "			</div>\n";
echo "			<div class='id'>\n";
echo "			Picture:\n";
echo "					<td><input type='file' name='fileUpload' value='fileUpload' >\n";
echo "					\n";
echo "			</div>	\n";
echo "		</div>	\n";
echo "			<input type='submit' value='Register!'>\n";
echo "			\n";
echo "	\n";
echo "	</form>\n";
echo "		  </div>\n";
echo "       \n";
echo "	   <div class=\"wrapper\">\n";
echo "          <footer>\n";
echo "              <ul class=\"links-main\">\n";
echo "                  <li><a href=\"home.html\">Home</a></li>\n";
echo "              </ul>\n";
echo "			    <span class='slogan'>\n";
echo "					Contact: (+63)9879654324<br>		\n";
echo "					E-mail:  customer@ernz.com\n";
echo "				</span>\n";
echo "        </div>		\n";
echo "    </body>\n";
echo "</html>\n";

?>
